config/routes.rb
Rails.application.routes.draw do
  get '/blogs', to: 'blog#index', as: 'blogs'
  get '/blogs/new', to: 'blog#new', as: 'new'
  post '/blogs', to: 'blog#create'
  get '/blogs/:id', to: 'blog#show', as: 'blog'
  get '/blogs/:id/edit', to: 'blog#edit', as: 'edit'
  patch '/blogs/:id', to: 'blog#update'
  delete '/blogs/:id', to: 'blog#delete', as: 'delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all 
    end
    def new
        @new_blog = Blog.new
    end
    def create
        @new_blog = Blog.create(blog_params)
        if @new_blog.valid?
            redirect_to blogs_path
        end
    end
    def show 
        @one_blog = Blog.find(params[:id])
    end
    def edit
        @modified_blog = Blog.find(params[:id])
    end
    def update
        @modified_blog = Blog.find(params[:id])
        @modified_blog.update(blog_params)
        if @modified_blog.valid?
            redirect_to blogs_path
        end
    end
    def delete
        @no_blog = Blog.find(params[:id])
        @no_blog.delete
        redirect_to blogs_path
    end

    private
    def blog_params
        params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h1> Edit Your Blog Post </h1>
<%= form_with model: @modified_blog, method: :patch do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <br>
    <%= form.label :content %>
    <%= form.text_field :content %>

    <br>
    <%= form.submit 'Edit Blog' %>
<% end %>
<%= link_to 'Back to List', blogs_path %>

app/views/blog/index.html.erb
<h1> Blog Post </h1>
<h2> Food Blog post </h2>
<ul>
<% @blogs.each do |post|%>
    <li>
        Title: <%= post.title %> Content: <%= post.content %>
    </li>
    <% end %>
</ul>

app/views/blog/new.html.erb
<h1> Suggest New Blog </h2>
<%= form_with model: @new_blog do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <br>
    <%= form.label :content %>
    <%= form.text_field :content %>

    <br>
    <%= form.submit 'Add Blog' %>
<% end %>
<%= link_to 'Back to List', blogs_path %>

app/views/blog/show.html.erb
<h1> Blog <%= @one_blog.id %> </h1>
<h2> <%= @one_blog.title %> </h1>
<h2> <%= @one_blog.content %> </h2>
<%= link_to 'Back to List', blogs_path %>
<%= button_to 'Delete this Blog', delete_path(@one_blog), method: :delete %>
# <%= link_to 'Edit Blog', edit_path(@one_blog) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFullStack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>